export interface Service {
  id: string;
  name: string;
  icon: string;
  url?: string;
  healthUrl?: string;
  description: string;
  port?: number;
  openInTab?: boolean;
}

export const services: Service[] = [
  {
    id: "agentsmith",
    name: "AgentSmith",
    icon: "🤖",
    url: "https://agentsmith.00raiser.space",
    healthUrl: "http://localhost:4000/health",
    description: "Workflow orchestration engine — the orchestra conductor",
    port: 3000,
  },
  {
    id: "krya",
    name: "Krya",
    icon: "🎨",
    url: "https://krya.00raiser.space",
    healthUrl: "http://localhost:3100/api/generations",
    description: "AI Creative Platform — image, video, 3D generation",
    port: 3100,
  },
  {
    id: "innotion",
    name: "INotion",
    icon: "📚",
    url: "https://inotion.00raiser.space",
    healthUrl: "http://localhost:3010",
    description: "Knowledge base — documents, creator profiles, intelligence",
    port: 3010,
    openInTab: true,
  },
  {
    id: "searxng",
    name: "SearXNG",
    icon: "🔍",
    url: "https://search.00raiser.space",
    healthUrl: "http://localhost:8888",
    description: "Self-hosted private meta search engine",
    port: 8888,
  },
  {
    id: "persona",
    name: "Persona Pipeline",
    icon: "🎭",
    url: "https://persona.00raiser.space",
    healthUrl: "http://localhost:8500/health",
    description: "Creator persona builder — agentified personalities",
    port: 8500,
  },
  {
    id: "cortex",
    name: "Cortex",
    icon: "🧠",
    url: "https://cortex.00raiser.space",
    healthUrl: "http://localhost:3011/health",
    description: "Neural network — activity tracking & task monitoring",
    port: 3011,
  },
  {
    id: "youtubedl",
    name: "YouTubeDL",
    icon: "📹",
    url: "https://dl.00raiser.space",
    healthUrl: "http://localhost:8200",
    description: "Video download & audio extraction",
    port: 8200,
  },
  {
    id: "whisperflow",
    name: "WhisperFlow",
    icon: "🎙️",
    url: "https://whisper.00raiser.space",
    healthUrl: "http://localhost:8766",
    description: "Speech-to-text transcription engine",
    port: 8766,
  },
  {
    id: "authentik",
    name: "Authentik",
    icon: "🔐",
    url: "https://auth.00raiser.space",
    healthUrl: "http://localhost:9000/-/health/ready/",
    description: "Identity provider — SSO & authentication",
    port: 9443,
  },
  {
    id: "content-intel",
    name: "Content Intel",
    icon: "📊",
    url: "https://content.00raiser.space",
    healthUrl: "http://localhost:3015/health",
    description: "Content intelligence — scraping, analysis, tracking",
    port: 3015,
    openInTab: true,
  },
  {
    id: "apify",
    name: "Apify Scraper",
    icon: "🕷️",
    url: "https://apify.00raiser.space",
    healthUrl: "http://localhost:8400",
    description: "Web scraping & data extraction engine",
    port: 8400,
    openInTab: true,
  },
  {
    id: "newsletter",
    name: "Newsletter",
    icon: "📬",
    url: "https://newsletter.00raiser.space",
    healthUrl: "http://localhost:8300/health",
    description: "Newsletter generation & distribution",
    port: 8300,
    openInTab: true,
  },
  {
    id: "agentsmith-admin",
    name: "AgentSmith Admin",
    icon: "⚡",
    url: "https://admin.00raiser.space",
    healthUrl: "http://localhost:4000/health",
    description: "AgentSmith administration & monitoring",
    port: 3001,
    openInTab: true,
  },
  {
    id: "gitea",
    name: "Gitea",
    icon: "🐙",
    url: "https://git.00raiser.space",
    healthUrl: "http://localhost:3003",
    description: "Self-hosted Git hosting & code collaboration",
    port: 3003,
    openInTab: true,
  },
  {
    id: "uptime-kuma",
    name: "Uptime Kuma",
    icon: "📡",
    url: "https://kuma.00raiser.space",
    healthUrl: "http://localhost:3002",
    description: "Uptime monitoring & status pages",
    port: 3002,
    openInTab: true,
  },
  {
    id: "stirling-pdf",
    name: "Stirling PDF",
    icon: "📄",
    url: "https://pdf.00raiser.space",
    healthUrl: "http://localhost:8081",
    description: "PDF tools — merge, split, convert, OCR",
    port: 8081,
    openInTab: true,
  },
  {
    id: "listmonk",
    name: "Listmonk",
    icon: "📧",
    url: "http://localhost:9090",
    healthUrl: "http://localhost:9090/health",
    description: "Newsletter & mailing list manager",
    port: 9090,
    openInTab: true,
  },
  {
    id: "umami",
    name: "Umami",
    icon: "📈",
    url: "http://localhost:3031",
    healthUrl: "http://localhost:3031",
    description: "Privacy-focused web analytics",
    port: 3031,
    openInTab: true,
  },
  {
    id: "changedetection",
    name: "Changedetection",
    icon: "🔔",
    url: "http://localhost:5555",
    healthUrl: "http://localhost:5555",
    description: "Website change detection & monitoring",
    port: 5555,
    openInTab: true,
  },
  {
    id: "crawlee",
    name: "Crawlee",
    icon: "🕸️",
    url: "http://localhost:3500",
    healthUrl: "http://localhost:3500",
    description: "Web crawling & scraping framework",
    port: 3500,
    openInTab: true,
  },
  {
    id: "minio",
    name: "MinIO",
    icon: "🗄️",
    url: "http://localhost:9100",
    healthUrl: "http://localhost:9100",
    description: "S3-compatible object storage",
    port: 9100,
    openInTab: true,
  },
  {
    id: "calcom",
    name: "Cal.com",
    icon: "📅",
    url: "http://localhost:3032",
    healthUrl: "http://localhost:3032",
    description: "Scheduling & calendar management",
    port: 3032,
    openInTab: true,
  },
  {
    id: "twenty",
    name: "Twenty",
    icon: "💼",
    url: "http://localhost:3030",
    healthUrl: "http://localhost:3030/healthz",
    description: "Open-source CRM",
    port: 3030,
    openInTab: true,
  },
  {
    id: "postiz",
    name: "Postiz",
    icon: "📱",
    url: "http://localhost:5100",
    healthUrl: "http://localhost:5100",
    description: "Social media scheduling & management",
    port: 5100,
    openInTab: true,
  },
  {
    id: "settings",
    name: "Settings",
    icon: "⚙️",
    description: "Portal configuration",
  },
];
