export interface Service {
  id: string;
  name: string;
  icon: string;
  url?: string;
  healthUrl?: string;
  description: string;
  port?: number;
  openInTab?: boolean;
}

export const services: Service[] = [
  {
    id: "agentsmith",
    name: "AgentSmith",
    icon: "🤖",
    url: "https://agentsmith.00raiser.space",
    healthUrl: "http://localhost:4000/health",
    description: "Workflow orchestration engine — the orchestra conductor",
    port: 3000,
  },
  {
    id: "krya",
    name: "Krya",
    icon: "🎨",
    url: "https://krya.00raiser.space",
    healthUrl: "http://localhost:3100/api/generations",
    description: "AI Creative Platform — image, video, 3D generation",
    port: 3100,
  },
  {
    id: "innotion",
    name: "InNotion",
    icon: "📚",
    url: "https://outline.00raiser.space",
    healthUrl: "http://localhost:3010",
    description: "Knowledge base — documents, creator profiles, intelligence",
    port: 3010,
    openInTab: true,
  },
  {
    id: "searxng",
    name: "SearXNG",
    icon: "🔍",
    url: "https://search.00raiser.space",
    healthUrl: "http://localhost:8888",
    description: "Self-hosted private meta search engine",
    port: 8888,
  },
  {
    id: "persona",
    name: "Persona Pipeline",
    icon: "🎭",
    url: "https://persona.00raiser.space",
    healthUrl: "http://localhost:8500/health",
    description: "Creator persona builder — agentified personalities",
    port: 8500,
  },
  {
    id: "cortex",
    name: "Cortex",
    icon: "🧠",
    url: "https://cortex.00raiser.space",
    healthUrl: "http://localhost:3011/health",
    description: "Neural network — activity tracking & task monitoring",
    port: 3011,
  },
  {
    id: "youtubedl",
    name: "YouTubeDL",
    icon: "📹",
    url: "https://dl.00raiser.space",
    healthUrl: "http://localhost:8200",
    description: "Video download & audio extraction",
    port: 8200,
  },
  {
    id: "whisperflow",
    name: "WhisperFlow",
    icon: "🎙️",
    url: "https://whisper.00raiser.space",
    healthUrl: "http://localhost:8766",
    description: "Speech-to-text transcription engine",
    port: 8766,
  },
  {
    id: "authentik",
    name: "Authentik",
    icon: "🔐",
    url: "https://auth.00raiser.space",
    healthUrl: "http://localhost:9000/-/health/ready/",
    description: "Identity provider — SSO & authentication",
    port: 9443,
  },
  {
    id: "content-intel",
    name: "Content Intel",
    icon: "📊",
    url: "https://content.00raiser.space",
    healthUrl: "http://localhost:3015/health",
    description: "Content intelligence — scraping, analysis, tracking",
    port: 3015,
    openInTab: true,
  },
  {
    id: "apify",
    name: "Apify Scraper",
    icon: "🕷️",
    url: "https://apify.00raiser.space",
    healthUrl: "http://localhost:8400",
    description: "Web scraping & data extraction engine",
    port: 8400,
    openInTab: true,
  },
  {
    id: "newsletter",
    name: "Newsletter",
    icon: "📬",
    url: "https://newsletter.00raiser.space",
    healthUrl: "http://localhost:8300/health",
    description: "Newsletter generation & distribution",
    port: 8300,
    openInTab: true,
  },
  {
    id: "agentsmith-admin",
    name: "AgentSmith Admin",
    icon: "⚡",
    url: "https://admin.00raiser.space",
    healthUrl: "http://localhost:4000/health",
    description: "AgentSmith administration & monitoring",
    port: 3001,
    openInTab: true,
  },
  {
    id: "settings",
    name: "Settings",
    icon: "⚙️",
    description: "Portal configuration",
  },
];
