#!/usr/bin/env python3
"""Build creator profile notebooks for each creator."""
import subprocess, json, time, os
from collections import Counter

LOG = "/home/eternity/.openclaw/workspace/Ultron/scripts/creator-profiles.log"
PROFILES_DIR = "/home/eternity/.openclaw/workspace/Ultron/media/creator-profiles"

def sql(q, user="content_intel"):
    r = subprocess.run(["docker","exec","raiser-postgres","psql","-U",user,"-d","raiser","-t","-A","-F","|","-c",q],
                       capture_output=True, text=True, timeout=30)
    return [l.strip() for l in r.stdout.strip().split('\n') if l.strip()]

def log(msg):
    ts = time.strftime('%Y-%m-%d %H:%M:%S')
    line = f"[{ts}] {msg}"
    print(line, flush=True)
    with open(LOG, 'a') as f:
        f.write(line + '\n')

def build_profile(cid):
    info = sql(f"SELECT name, handle, platform, subscriber_count, COALESCE(metadata::text,'{{}}') FROM content.creators WHERE id = {cid}")
    if not info: return None
    parts = info[0].split('|')
    name, handle, platform = parts[0], parts[1], parts[2]
    subs = int(parts[3]) if parts[3] else 0
    
    stats = sql(f"""SELECT 
        COUNT(*),
        COUNT(CASE WHEN description IS NOT NULL AND description != '' AND description != '[no transcript]' THEN 1 END),
        COALESCE(SUM(COALESCE((metrics->>'viewCount')::bigint, 0)), 0)
        FROM content.content WHERE creator_id = {cid}""")
    total, transcribed, total_views = 0, 0, 0
    if stats:
        p = stats[0].split('|')
        total, transcribed, total_views = int(p[0]), int(p[1]), int(p[2])

    # Top content
    top_rows = sql(f"""SELECT title || '|||' || external_id || '|||' || COALESCE((metrics->>'viewCount')::text,'0') || '|||' || COALESCE(published_at::text,'')
        FROM content.content WHERE creator_id = {cid}
        ORDER BY COALESCE((metrics->>'viewCount')::bigint, 0) DESC LIMIT 10""")
    top = []
    for row in top_rows:
        p = row.split('|||')
        top.append({'title': p[0], 'id': p[1] if len(p)>1 else '', 'views': p[2] if len(p)>2 else '0', 'date': p[3][:10] if len(p)>3 else ''})

    # Topics from titles
    titles = sql(f"SELECT title FROM content.content WHERE creator_id = {cid} AND title IS NOT NULL LIMIT 200")
    stopwords = {'the','a','an','in','on','at','to','for','of','and','is','it','this','that','with','how','what','why','i','my','your','we','our','you','from','are','was','has','have','not','but','can','will','just','about','more','all','been','its','new','one','out','get','like','make'}
    words = Counter()
    for t in titles:
        for w in t.lower().split():
            w = w.strip('.,!?|:;()[]"\'-#@')
            if len(w) > 3 and w not in stopwords and not w.isdigit():
                words[w] += 1
    topics = [w for w, _ in words.most_common(20)]

    md = f"""# {name}

## Overview
| Field | Value |
|-------|-------|
| Handle | @{handle} |
| Platform | {platform} |
| Subscribers | {subs:,} |
| Total Content | {total} videos |
| Transcripts | {transcribed} / {total} ({transcribed*100//max(total,1)}%) |
| Total Views | {total_views:,} |

## Key Topics
{', '.join(topics) if topics else '_Pending — no content scraped yet_'}

## Top Content (by views)
"""
    for i, c in enumerate(top, 1):
        md += f"{i}. **{c['title']}** — {int(c['views']) if c['views'].isdigit() else 0:,} views ({c['date']})\n"
        md += f"   https://youtube.com/watch?v={c['id']}\n\n"

    md += f"""
## Persona Profile
_Status: {'Ready for generation' if transcribed >= 10 else 'Pending — need more transcripts'}_
- Transcripts available: {transcribed}
- Minimum needed: 10

## Content Patterns
- Avg views per video: {total_views//max(total,1):,}
- Content focus: {', '.join(topics[:5]) if topics else 'TBD'}

---
_Auto-generated by Ultron Creator Intelligence Pipeline — {time.strftime('%Y-%m-%d %H:%M')}_
"""
    return name, md

def main():
    os.makedirs(PROFILES_DIR, exist_ok=True)
    creators = sql("SELECT id FROM content.creators ORDER BY id")
    log(f"Building profiles for {len(creators)} creators")
    
    built = 0
    for cid in creators:
        result = build_profile(int(cid))
        if result:
            name, md = result
            safe = name.replace(' ', '-').replace('/', '-').replace("'", "")
            path = os.path.join(PROFILES_DIR, f"{safe}.md")
            with open(path, 'w') as f:
                f.write(md)
            built += 1
            log(f"✅ {name} ({path})")
    
    log(f"COMPLETE: {built}/{len(creators)} profiles built")

if __name__ == "__main__":
    main()
